/**
 * Little tidbits of past events generated by the player doing things.
 *
 * Can be used in engravings, dreams, and changeling succs.
 * All generated text is anonymized for persistence safety.
 *
 * ## Creating a new memory
 * 1. Subtype `/datum/memory`
 * 2. Set `name_templates` and `start_templates` (lists of strings with {PLACEHOLDER} tokens)
 * 3. Set `story_value` and `memory_flags` as needed
 * 4. Optionally set `associated_mood_category` + `associated_mood_type` for auto mood coupling
 * 5. Optionally override `post_init()` for runtime logic
 *
 * Custom data is passed as extra named args at the call site and stored in `extra_data`.
 * Any key in extra_data is available as `{UPPERCASE_KEY}` in templates.
 */
/datum/memory
	/// Display name shown in the memory panel.
	var/name

	// === TEMPLATES ===
	/// List of possible name strings with {PLACEHOLDER} support.
	var/list/name_templates
	/// List of possible story start strings for engravings/tattoos/etc.
	var/list/start_templates
	/// List of possible location phrase strings. Defaults provided on base type.
	var/list/location_templates = list("in {WHERE_ADJ}.", "while in {WHERE}.")

	// === CHARACTER DATA ===
	/// The main character / doer of the action.
	var/datum/memory_character/subject_character
	/// The secondary character / receiver of the action.
	var/datum/memory_character/target_character
	/// The tertiary element / thing involved.
	var/datum/memory_character/object_character

	// === LOCATION DATA ===
	/// Name of the area where this memory took place.
	var/area_name
	/// Adjectives describing the area at the time of creation.
	var/list/location_adjectives

	// === EXTRA DATA ===
	/// Generic dict for custom template keys (e.g., "surgery_type" = "appendectomy").
	var/list/extra_data

	// === MOOD COUPLING ===
	/// If set, adding this memory also adds a mood event with this category.
	var/associated_mood_category
	/// The mood event type path to fire. Requires associated_mood_category.
	var/associated_mood_type
	/// Which extra_data keys to forward as args to the mood event's add_effects().
	var/list/mood_arg_keys

	/// Defines how beautiful art from it can be, and whether or not it stays in persistence.
	var/story_value = STORY_VALUE_NONE
	/// Flags of any special behavior for the memory
	var/memory_flags = NONE
	/// The mind that created this memory.
	var/datum/mind/memorizer_mind
	/// Anonymized name of the memorizer.
	var/memorizer_name

/datum/memory/New(
	datum/mind/memorizer_mind,
	atom/subject,
	atom/target,
	atom/object_atom,
	list/extra_data
)
	src.memorizer_mind = memorizer_mind
	src.extra_data = extra_data

	// Default subject to the memorizer's mob
	if(isnull(subject))
		subject = memorizer_mind?.current

	// Build character data with adjectives captured RIGHT NOW
	src.subject_character = build_memory_character(subject)
	src.target_character = build_memory_character(target)
	src.object_character = build_memory_character(object_atom)

	// Build memorizer info
	src.memorizer_name = build_character_name(memorizer_mind)

	// Build location info
	if(!(memory_flags & MEMORY_FLAG_NOLOCATION) && subject && isatom(subject))
		var/turf/subject_turf = get_turf(subject)
		var/area/subject_area = get_area(subject_turf)
		src.area_name = subject_area?.name
		src.location_adjectives = collect_location_adjectives(subject_turf)

	// Hook for subtypes that need runtime logic
	post_init()

	// Generate the display name
	generate_memory_name()

/datum/memory/Destroy(force)
	memorizer_mind = null
	return ..()

/datum/memory/serialize_list(list/options, list/semvers)
	. = ..()
	.["name"] = name
	.["memorizer"] = memorizer_name
	.["story_value"] = story_value
	.["memory_flags"] = memory_flags
	.["subject_name"] = subject_character?.name
	.["target_name"] = target_character?.name
	.["object_name"] = object_character?.name
	.["where"] = area_name
	SET_SERIALIZATION_SEMVER(semvers, "2.0.0")
	return .

/**
 * Hook for subtypes to run logic after all fields are populated.
 * Use this instead of overriding New() for things like modifying story_value based on extra_data.
 */
/datum/memory/proc/post_init()
	return

/**
 * Generates a name for the memory.
 */
/datum/memory/proc/generate_memory_name()
	if(!length(name_templates))
		name = "Erroneous memory - This is a bug"
		story_value = STORY_VALUE_SHIT
		memory_flags |= (MEMORY_FLAG_NOPERSISTENCE|MEMORY_NO_STORY)
		return

	name = capitalize(resolve_template(pick(name_templates)))

/**
 * Resolves all {PLACEHOLDER} tokens in a template string.
 *
 * Standard tokens: SUBJECT, SUBJECT_ADJ, TARGET, TARGET_ADJ, OBJECT, OBJECT_ADJ,
 * WHERE, WHERE_ADJ, MEMORIZER, STATION.
 * Any key in extra_data is also available as {UPPERCASE_KEY}.
 * An optional extra_context list can provide additional tokens (used by story generation).
 */
/datum/memory/proc/resolve_template(template, list/extra_context)
	var/result = template

	// Character tokens
	result = replacetext(result, "{SUBJECT}", subject_character?.name || "someone")
	result = replacetext(result, "{SUBJECT_ADJ}", subject_character?.describe() || "someone")
	result = replacetext(result, "{TARGET}", target_character?.name || "someone")
	result = replacetext(result, "{TARGET_ADJ}", target_character?.describe() || "someone")
	result = replacetext(result, "{OBJECT}", object_character?.name || "something")
	result = replacetext(result, "{OBJECT_ADJ}", object_character?.describe() || "something")

	// Location tokens
	result = replacetext(result, "{WHERE}", area_name || "somewhere")
	result = replacetext(result, "{WHERE_ADJ}", describe_location())

	// Memorizer
	result = replacetext(result, "{MEMORIZER}", memorizer_name || "someone")

	// Station info
	result = replacetext(result, "{STATION}", station_name())

	// Extra data tokens (keys uppercased for template matching)
	for(var/key in extra_data)
		result = replacetext(result, "{[uppertext(key)]}", "[extra_data[key]]")

	// Story generation context (SOMETHING, CREWMEMBER, etc.)
	for(var/key in extra_context)
		result = replacetext(result, "{[key]}", "[extra_context[key]]")

	return result

/**
 * Returns a location phrase with adjectives, e.g. "the dim, filthy Medbay"
 */
/datum/memory/proc/describe_location()
	if(!area_name)
		return "somewhere"
	if(!length(location_adjectives))
		return area_name
	var/adj = pick(location_adjectives)
	return "the [adj] [area_name]"

/**
 * Generates a story based on this memory.
 *
 * Arguments
 * * story_type - for used in grabbing phrases from memories.json involving specific types of stories.
 * * story_flags - any additional flags involving the story
 */
/datum/memory/proc/generate_story(story_type, story_flags)
	// Grab the data pools for this story type
	var/list/forewords = GLOB.story_forewords[story_type]
	var/list/styles
	if(!(story_flags & STORY_FLAG_NO_STYLE))
		styles = GLOB.story_styles["generic"]?.Copy()
		if(GLOB.story_styles[story_type])
			LAZYADD(styles, GLOB.story_styles[story_type])

	// Context for style resolution
	var/list/story_context = list("STORY_TYPE" = story_type)

	// Build the story pieces
	var/list/story_pieces = list()

	// The forewords for this specific type of story (E.g. This engraving depicts)
	story_pieces += pick(forewords)

	// The story start for this specific action. (E.g. The Chef carving into The Clown)
	story_pieces += resolve_template(pick(start_templates))

	// The location it happend, which isn't always included, but commonly is. (E.g. in Space, while in the Bar)
	if(!(memory_flags & MEMORY_FLAG_NOLOCATION) && length(location_templates))
		story_pieces += resolve_template(pick(location_templates))

	// Explains any unique styling the art has. e.g. (The engraving has a cubist style.)
	if(length(styles) && prob(75))
		story_pieces += resolve_template(pick(styles), story_context)

	var/parsed_story = ""
	var/capitalize_next_line = FALSE
	for(var/line in story_pieces)
		if(capitalize_next_line)
			line = capitalize(line)
			capitalize_next_line = FALSE

		if(line[length(line)] == ".")//End of sentence, next sentence needs to start with a capital.'
			capitalize_next_line = TRUE
		if(line != story_pieces[story_pieces.len]) //not the last line
			parsed_story += "[line] "

	//after replacement section for performance
	if(story_flags & STORY_FLAG_DATED)
		if(memory_flags & MEMORY_FLAG_NOSTATIONNAME)
			parsed_story += "This took place in [time2text(world.realtime, "Month", NO_TIMEZONE)] of [CURRENT_STATION_YEAR]."
		else
			parsed_story += "This took place in [time2text(world.realtime, "Month", NO_TIMEZONE)] of [CURRENT_STATION_YEAR] on [station_name()]."

	parsed_story = trim_right(parsed_story)
	return parsed_story

/**
 * Creates a quick copy of this memory for another mind (e.g., changeling absorb).
 * Quick copies cannot be used for stories.
 */
/datum/memory/proc/quick_copy_memory(datum/mind/new_memorizer)
	return new /datum/memory/copy(new_memorizer, src)

// === COPY SUBTYPE ===

/// Shallow copy of a memory, used by changeling absorb and similar. Cannot generate stories.
/datum/memory/copy
	memory_flags = MEMORY_NO_STORY

/datum/memory/copy/New(datum/mind/new_memorizer, datum/memory/source)
	memorizer_mind = new_memorizer
	name = source.name
	story_value = source.story_value
	memory_flags = source.memory_flags | MEMORY_NO_STORY
	subject_character = source.subject_character
	target_character = source.target_character
	object_character = source.object_character
	area_name = source.area_name
	// Skip parent New() entirely — we're copying, not creating

/datum/memory/copy/generate_memory_name()
	return // We just copy the original memory's name anyways

/datum/memory/copy/post_init()
	return
